# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build, test, and release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [ 2.7 ]
    steps:
    - uses: actions/checkout@v2
    ############ Release ###############
    - name: Get tag
      id: tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Install conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: false
        activate-conda: true
    - name: Replace version with tag - macos
      if: ${{ matrix.os == 'macos-latest' }}
      env:
        SOURCE_TAG: ${{ steps.tag.outputs.SOURCE_TAG }}
      run: sed -i "" -e "s/development/${SOURCE_TAG}/" main.cpp methratio.py conda/meta.yaml
    - name: Replace version with tag - linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      env:
        SOURCE_TAG: ${{ steps.tag.outputs.SOURCE_TAG }}
      run: sed -i "s/development/${SOURCE_TAG}/" main.cpp methratio.py conda/meta.yaml
    - name: Build conda package
      env:
        SOURCE_TAG: ${{ steps.tag.outputs.SOURCE_TAG }}
      run: |
        env | grep "CONDA"
        conda install conda-build anaconda-client
        echo Got tag $SOURCE_TAG
        cd conda && conda build --python ${{ matrix.python-version }} -c bioconda -c conda-forge -c defaults .
        anaconda -t ${{ secrets.CONDA_TOKEN }} upload ${CONDA}/conda-bld/*/bsmapz-${SOURCE_TAG}*
