# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build, test, and release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    ############ Release ###############
    - name: Get tag
      id: tag
      run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Install conda
      if: ${{ steps.tag.outputs.SOURCE_TAG != '' }}
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: false
        activate-conda: true
    - name: Build conda package
      if: ${{ steps.tag.outputs.SOURCE_TAG != '' }}
      env:
        SOURCE_TAG: ${{ steps.tag.outputs.SOURCE_TAG }}
      run: |
        conda config --set anaconda_upload yes
        conda install conda-build anaconda-client
        anaconda -t ${{ secrets.CONDA_TOKEN }} login
        echo Got tag $SOURCE_TAG
        sed -i "s/development/${SOURCE_TAG}/" main.cpp methratio.py conda/meta.yaml
        make conda
